'use strict';
const crypto=require('crypto');
const manifest=require('./manifest');
const {validate,requestFor}=require('../bmod/router');
const BASE='https://api.canva.com/rest/v1';
const AUTH='https://www.canva.com/api/oauth/authorize';
const own=(o,k)=>Object.prototype.hasOwnProperty.call(o,k);
const delay=ms=>new Promise(r=>setTimeout(r,ms));
function createService({sbRest,sbRpc,getSecret,getRefreshSecret,fetchImpl=(...args)=>fetch(...args),env=process.env,insertActionStep,nextActionStepOrder}) {
 const filter=user=>`user_id=eq.${encodeURIComponent(user)}&integration_key=eq.canva`;
 const row=async user=>(await sbRest(`user_connections?${filter(user)}&select=*&limit=1`))?.[0]||null;
 const transition=(user,action,lease=null,data={})=>sbRpc('canva_token_transition',{p_user_id:user,p_action:action,p_lease:lease,p_data:data});
 function credentials(){if(!env.CANVA_CLIENT_ID||!env.CANVA_CLIENT_SECRET)throw Error('Canva setup is incomplete. Add CANVA_CLIENT_ID and CANVA_CLIENT_SECRET to the server environment.');return {authorization:`Basic ${Buffer.from(`${env.CANVA_CLIENT_ID}:${env.CANVA_CLIENT_SECRET}`).toString('base64')}`,'content-type':'application/x-www-form-urlencoded'};}
 async function oauth(path,params){const response=await fetchImpl(BASE+path,{method:'POST',headers:credentials(),body:new URLSearchParams(params).toString(),signal:AbortSignal.timeout(15000)});let data;try{data=await response.json();}catch{data={};}return {response,data};}
 async function save(user,lease,data){if(!data.access_token||!data.refresh_token||!(Number(data.expires_in)>0))throw Error('Canva returned incomplete credentials.');for(let i=0;i<3;i++){try{if(!await transition(user,'save',lease,data))throw Error('Authorization changed.');return;}catch{if(i===2)throw Error('Could not securely save Canva authorization.');await delay(100*(i+1));}}}
 async function token(user,rejected=null){let lease=null;for(let i=0;i<30;i++){const c=await row(user);if(c?.status!=='connected')throw Error('Connect Canva to continue.');const access=await getSecret(user,'canva');if(access&&Date.parse(c.token_expires_at)>Date.now()+300000&&(!rejected||access!==rejected))return access;const candidate=crypto.randomUUID();if(await transition(user,'claim',candidate)){lease=candidate;break;}await delay(200);}if(!lease)throw Error('Canva authorization is refreshing. Retry shortly.');try{const c=await row(user),access=await getSecret(user,'canva');if(c?.status!=='connected')throw Error('Canva was disconnected.');if(access&&Date.parse(c.token_expires_at)>Date.now()+300000&&(!rejected||access!==rejected))return access;const refresh=await getRefreshSecret(user,'canva');if(!refresh)throw Error('Canva refresh credentials are unavailable.');const {response,data}=await oauth('/oauth/token',{grant_type:'refresh_token',refresh_token:refresh});if(!response.ok){if([400,401].includes(response.status)&&(data.error==='invalid_grant'||data.code==='invalid_grant'))await transition(user,'revoke',lease);throw Error(`Canva refresh failed (${response.status}).`);}await save(user,lease,data);return data.access_token;}finally{await transition(user,'release',lease).catch(()=>{});}}
 async function api(user,op,request){let access=await token(user);for(let attempt=0;attempt<2;attempt++){const c=await row(user);if(c?.status!=='connected')throw Error('Canva was disconnected.');if(op.scopes.some(s=>!manifest.parseScopes(c.oauth_scope).has(s)))throw Error('Update Permissions for Canva. Your connection remains active.');if(op.classification==='write'&&manifest.modeOf(c)!=='view_and_take_action')throw Error('Canva is View Only.');const r=await fetchImpl(BASE+request.path,{method:request.method||'GET',headers:{authorization:`Bearer ${access}`,'content-type':'application/json'},body:request.body?JSON.stringify(request.body):undefined,signal:AbortSignal.timeout(15000)});if(r.status===401&&attempt===0&&op.classification==='read'){await r.text();access=await token(user,access);continue;}let data;try{data=await r.json();}catch{data=null;}if(!r.ok)throw Error(r.status===403?'Canva denied this operation. Check permissions and Canva plan availability.':`Canva request failed (${r.status}).`);return data;}}
 async function start(user,site,returnUrl){credentials();const c=await row(user);if(c?.status==='connected'&&!manifest.capabilities(c).reauthorization_required)return {status:'connected'};await sbRest('user_connections?on_conflict=user_id,integration_key',{method:'POST',headers:{Prefer:'resolution=ignore-duplicates,return=minimal'},body:JSON.stringify([{user_id:user,integration_key:'canva',transport:'http',server_url:BASE,status:'auth_required',read_only:true}])});await sbRest(`user_connections?${filter(user)}&status=in.(disabled,disconnected,error)`,{method:'PATCH',body:JSON.stringify({status:'auth_required'})});const state=crypto.randomBytes(32).toString('base64url'),verifier=crypto.randomBytes(48).toString('base64url'),redirect=`${site}/api/connections/canva/callback`,scopes=manifest.scopesForMode(manifest.modeOf(c)).join(' ');await sbRest('connection_oauth_states',{method:'POST',body:JSON.stringify([{state,user_id:user,integration_key:'canva',code_verifier:verifier,redirect_uri:redirect,return_url:returnUrl,client_id:env.CANVA_CLIENT_ID,token_endpoint:BASE+'/oauth/token',authorization_endpoint:AUTH,scopes,token_auth_method:'client_secret_basic',expires_at:new Date(Date.now()+600000).toISOString()}])});const url=new URL(AUTH);for(const [k,v] of Object.entries({response_type:'code',client_id:env.CANVA_CLIENT_ID,redirect_uri:redirect,scope:scopes,state,code_challenge_method:'S256',code_challenge:crypto.createHash('sha256').update(verifier).digest('base64url')}))url.searchParams.set(k,v);return {authorizeUrl:url.href};}
 async function callback(state,code,error){if(!state||state.length>200)return null;const states=await sbRest(`connection_oauth_states?state=eq.${encodeURIComponent(state)}&integration_key=eq.canva`,{method:'DELETE',headers:{Prefer:'return=representation'}}),st=states?.[0];if(!st)return null;const result={returnUrl:st.return_url,ok:false};if(error||!code||Date.parse(st.expires_at)<Date.now()||st.client_id!==env.CANVA_CLIENT_ID)return result;const lease=crypto.randomUUID();if(!await transition(st.user_id,'claim',lease))return result;try{const {response,data}=await oauth('/oauth/token',{grant_type:'authorization_code',code,code_verifier:st.code_verifier,redirect_uri:st.redirect_uri});if(!response.ok)throw Error('Canva code exchange failed.');await save(st.user_id,lease,{...data,scope:typeof data.scope==='string'?data.scope:'',requested_scope:st.scopes,client_id:st.client_id,mode:'callback'});if(typeof data.scope!=='string'){try{const info=await oauth('/oauth/introspect',{token:data.access_token});if(info.response.ok&&info.data.active===true&&typeof info.data.scope==='string')await transition(st.user_id,'scopes',lease,{scope:info.data.scope});}catch{}}result.ok=true;}catch{ /* Provider details and credentials never go to logs or the browser. */ }finally{await transition(st.user_id,'release',lease).catch(()=>{});}return result;}
 async function execute(user,args,context={}){const c=await row(user);if(c?.status!=='connected')throw Error('Connect Canva to continue.');if(args.operation==='describe_operations')return manifest.capabilities(c);if(!own(manifest.operations,args.operation))throw Error('Unsupported Canva operation.');let parameters;try{parameters=JSON.parse(args.parameters_json||'{}');}catch{throw Error('Parameters must be a JSON object.');}const op=manifest.operations[args.operation],values=validate(op,parameters);if(op.classification==='write'&&manifest.modeOf(c)!=='view_and_take_action')return {error:'view_only',executed:false};if(op.scopes.some(s=>!manifest.parseScopes(c.oauth_scope).has(s)))return {error:'reauthorization_required',executed:false,message:'Choose Update Permissions in Connections. Canva remains connected.'};if(op.classification==='read')return api(user,op,requestFor(op,values,'unused'));
 if(values.width*values.height>25000000)throw Error('Design area must not exceed 25 million pixels.');
 const payload={type:'type_and_asset',title:values.title,design_type:{type:'custom',width:values.width,height:values.height},...(values.asset_id?{asset_id:values.asset_id}:{})};
 if(values.asset_id)await api(user,manifest.operations.get_asset,{path:'/assets/'+encodeURIComponent(values.asset_id)});
 if(!context.runId)return {status:'prepared',executed:false,parameters:values,message:'Design specification validated. Switch to Action Mode and request this design to queue individual approval.'};
 const step=await insertActionStep({user_id:user,run_id:context.runId,step_order:await nextActionStepOrder(context.runId),step_type:'external_action',title:`Create Canva design: ${values.title}`,description:`Create one ${values.width} × ${values.height} design${values.asset_id?' with image asset '+values.asset_id:''}. No publishing or export.`,status:'blocked',external_system:'Canva',proposed_action:{operation:'create_design',parameters:values},approval_status:'pending',result:{note:'Awaiting your approval. Nothing created.'}});
 await sbRest('canva_design_actions',{method:'POST',body:JSON.stringify([{step_id:step.id,user_id:user,connection_epoch:c.oauth_connected_at,payload,status:'pending'}])});return {status:'approval_required',executed:false,step_id:step.id,parameters:values};}
 async function approve(user,stepId,decision){const rows=await sbRest(`canva_design_actions?step_id=eq.${encodeURIComponent(stepId)}&user_id=eq.${encodeURIComponent(user)}&select=*`),action=rows?.[0];if(!action)return null;if(action.status!=='pending')return {ok:false,note:'This Canva approval has already been handled. It will not execute again.'};
 const c=await row(user);if(decision==='approve'&&(c?.status!=='connected'||c.oauth_connected_at!==action.connection_epoch||manifest.modeOf(c)!=='view_and_take_action'))return {ok:false,note:'Canva connection or permission mode changed. Prepare a new action.'};
 const claimed=await sbRest(`canva_design_actions?step_id=eq.${encodeURIComponent(stepId)}&user_id=eq.${encodeURIComponent(user)}&status=eq.pending`,{method:'PATCH',headers:{Prefer:'return=representation'},body:JSON.stringify({status:decision==='approve'?'executing':'rejected'})});if(!claimed?.length)return {ok:false,note:'This approval is already being processed.'};
 let result={note:'Rejected. Nothing created.'},status='blocked',actionStatus='rejected';
 if(decision==='approve'){try{const data=await api(user,manifest.operations.prepare_design,{path:'/designs',method:'POST',body:action.payload});if(!data?.design?.id)throw Error('Creation result not confirmed.');result={note:'Canva design created.',design_id:data.design.id};actionStatus='created';try{const checked=await api(user,manifest.operations.get_design,{path:'/designs/'+encodeURIComponent(data.design.id)});if(checked?.design?.id!==data.design.id)throw Error('Cannot verify');const edit=checked.design.urls?.edit_url;result={...result,verified:true,...(typeof edit==='string'&&/^https:\/\/(www\.)?canva\.com\//.test(edit)?{edit_url:edit}:{})};}catch{result.verified=false;result.note='Design created; read-back verification unavailable. Do not create another copy.';}status='completed';}catch{actionStatus='unknown';result={note:'Creation could not be confirmed. Check Canva before preparing another action; this approval will not retry.'};}}
 await sbRest(`canva_design_actions?step_id=eq.${encodeURIComponent(stepId)}&user_id=eq.${encodeURIComponent(user)}`,{method:'PATCH',body:JSON.stringify({status:actionStatus,result})});await sbRest(`action_steps?id=eq.${encodeURIComponent(stepId)}&user_id=eq.${encodeURIComponent(user)}`,{method:'PATCH',body:JSON.stringify({approval_status:decision==='approve'?'approved':'rejected',status,result,updated_at:new Date().toISOString()})});return {ok:actionStatus==='created'||actionStatus==='rejected',approved:decision==='approve',note:result.note,result};}
 async function disconnect(user){await transition(user,'disconnect');return {ok:true,status:'disconnected'};}
 async function verify(user){const checks=[];for(const operation of ['list_designs','list_brand_templates']){try{const result=await execute(user,{operation,parameters_json:'{}'});checks.push({operation,status:result?.error?'missing_permission':'passed'});}catch{checks.push({operation,status:'failed'});}}return {status:(await row(user))?.status,checks};}
 return {row,start,callback,token,execute,approve,disconnect,verify,transition,api};
}
module.exports={createService};
