const {test}=require('node:test');const assert=require('node:assert/strict');
const {createService}=require('../canva/service');const m=require('../canva/manifest');
function fixture(options={}){
 let c={status:'connected',permission_mode:'view_only',oauth_scope:m.scopesForMode('view_only').join(' '),token_expires_at:new Date(Date.now()+3600000).toISOString(),oauth_connected_at:'2026-09-22T00:00:00.000Z'},access='old-access',refresh='old-refresh',lease=null,states=[],actions=[],steps=[],calls=[],saveFailures=options.saveFailures||0;
 const response=(data,status=200)=>({ok:status<300,status,json:async()=>data,text:async()=>JSON.stringify(data)});
 const sbRest=async(path,opts={})=>{const [table,query]=path.split('?'),q=new URLSearchParams(query),body=opts.body?JSON.parse(opts.body):null;
 if(table==='user_connections'){if(opts.method==='PATCH'){if(q.has('status')&&!q.get('status').slice(4,-1).split(',').includes(c.status))return [];Object.assign(c,body);return [];}return [{...c}];}
 if(table==='connection_oauth_states'){if(opts.method==='POST'){states.push(...body);return [];}const matches=states.filter(s=>q.get('state')==='eq.'+s.state);if(opts.method==='DELETE')states=states.filter(s=>!matches.includes(s));return matches;}
 if(table==='canva_design_actions'){if(opts.method==='POST'){actions.push(...body);return [];}const a=actions.find(a=>q.get('step_id')==='eq.'+a.step_id&&q.get('user_id')==='eq.'+a.user_id);if(!a||(q.get('status')&&q.get('status')!=='eq.'+a.status))return [];if(opts.method==='PATCH')Object.assign(a,body);return [{...a}];}
 if(table==='action_steps')return [];
 throw Error('Unexpected DB route '+table);};
 const sbRpc=async(name,p)=>{assert.equal(name,'canva_token_transition');const a=p.p_action;if(a==='disconnect'){c.status='disabled';access=refresh=null;states=[];lease=null;return true;}if(['disabled','disconnected'].includes(c.status))return false;if(a==='claim'){if(lease)return false;lease=p.p_lease;return true;}if(lease!==p.p_lease)return false;if(a==='release'){lease=null;return true;}if(a==='revoke'){c.status='auth_required';return true;}if(a==='scopes'){c.oauth_scope=p.p_data.scope;return true;}if(a==='save'){if(saveFailures-->0)throw Error('temporary storage error');access=p.p_data.access_token;refresh=p.p_data.refresh_token;c.token_expires_at=new Date(Date.now()+3600000).toISOString();if('scope'in p.p_data)c.oauth_scope=p.p_data.scope;c.status='connected';return true;}throw Error('Unknown transition');};
 const fetchImpl=async(url,opts)=>{calls.push({url,opts});if(options.fetch){const custom=await options.fetch(url,opts);if(custom)return custom;}if(url.endsWith('/oauth/token')){assert.ok(opts.headers.authorization.startsWith('Basic '));const form=new URLSearchParams(opts.body);if(form.get('grant_type')==='refresh_token')assert.equal(form.get('refresh_token'),refresh);return response({access_token:'new-access-'+calls.length,refresh_token:'new-refresh-'+calls.length,expires_in:3600,...(options.omitScope?{}:{scope:options.scope??c.oauth_scope})});}if(url.endsWith('/oauth/introspect'))return response({active:true,scope:m.scopesForMode('view_only').join(' ')});if(url.endsWith('/designs')&&opts.method==='POST')return response({design:{id:'D123'}});if(url.endsWith('/designs/D123'))return response({design:{id:'D123',urls:{edit_url:'https://www.canva.com/design/D123/edit'}}});return response({items:[]});};
 const svc=createService({sbRest,sbRpc,getSecret:async()=>access,getRefreshSecret:async()=>refresh,fetchImpl,env:options.env??{CANVA_CLIENT_ID:'fixed-client',CANVA_CLIENT_SECRET:'test-secret'},insertActionStep:async step=>{const s={...step,id:'step-'+steps.length};steps.push(s);return s;},nextActionStepOrder:async()=>steps.length+1});
 return {svc,c,calls,steps,actions,response,states:()=>states};
}
const args=(operation,parameters={})=>({operation,parameters_json:JSON.stringify(parameters)});
const design={title:'Test design',width:1080,height:1080};
test('fixed Canva OAuth uses S256, curated scopes, single-use state and secure callback',async()=>{const f=fixture();f.c.status='auth_required';const start=await f.svc.start('user','https://marina.example','https://marina.example/');const u=new URL(start.authorizeUrl);assert.equal(u.origin,'https://www.canva.com');assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.equal(u.searchParams.get('client_id'),'fixed-client');assert.equal(u.searchParams.get('redirect_uri'),'https://marina.example/api/connections/canva/callback');assert.equal(u.searchParams.get('scope'),m.scopesForMode('view_only').join(' '));assert.ok(!start.authorizeUrl.includes(f.states()[0].code_verifier));assert.equal((await f.svc.callback(u.searchParams.get('state'),'code',null)).ok,true);assert.equal(await f.svc.callback(u.searchParams.get('state'),'code',null),null);assert.equal(f.c.status,'connected');});
test('missing client configuration does not reset an existing connection',async()=>{const f=fixture({env:{}});await assert.rejects(f.svc.start('user','https://marina.example','/'),/setup/);assert.equal(f.c.status,'connected');});
test('upgrade cancellation and expired callback preserve connected status',async()=>{const f=fixture();f.c.permission_mode='view_and_take_action';await f.svc.start('user','https://marina.example','/');assert.equal((await f.svc.callback(f.states()[0].state,'','access_denied')).ok,false);assert.equal(f.c.status,'connected');await f.svc.start('user','https://marina.example','/');f.states()[0].expires_at='2000-01-01';assert.equal((await f.svc.callback(f.states()[0].state,'code',null)).ok,false);assert.equal(f.calls.length,0);});
test('read, fresh connection read, expiry, concurrent rotation, and repeated reads',async()=>{const f=fixture();assert.equal((await f.svc.verify('user')).checks.every(c=>c.status==='passed'),true);assert.equal((await f.svc.row('user')).status,'connected');f.c.token_expires_at='2000-01-01';await Promise.all([f.svc.execute('user',args('list_designs')),f.svc.execute('user',args('list_brand_templates'))]);assert.equal(f.calls.filter(c=>c.url.endsWith('/oauth/token')).length,1);assert.equal((await f.svc.verify('user')).checks.every(c=>c.status==='passed'),true);});
test('rotated token storage retries same pair; omitted refresh scopes preserved',async()=>{const f=fixture({saveFailures:1,omitScope:true});f.c.token_expires_at='2000-01-01';await f.svc.token('user');assert.equal(f.calls.filter(c=>c.url.endsWith('/oauth/token')).length,1);assert.equal(f.c.oauth_scope,m.scopesForMode('view_only').join(' '));});
test('narrowed refresh grant stops resource call without disconnect',async()=>{const f=fixture({scope:'asset:read'});f.c.token_expires_at='2000-01-01';await assert.rejects(f.svc.execute('user',args('list_designs')),/Permissions/);assert.equal(f.c.status,'connected');assert.equal(f.calls.length,1);});
test('missing scope, View Only, invalid parameters and unsupported writes fail closed',async()=>{const f=fixture();assert.equal((await f.svc.execute('user',args('prepare_design',design))).error,'view_only');f.c.oauth_scope='';assert.equal((await f.svc.execute('user',args('list_designs'))).error,'reauthorization_required');await assert.rejects(f.svc.execute('user',args('delete_design')),/Unsupported/);await assert.rejects(f.svc.execute('user',args('list_designs',{url:'https://evil.example'})),/Unsupported/);assert.equal(f.calls.length,0);});
test('prepare never writes; Action Mode approval creates once and verifies result',async()=>{const f=fixture();f.c.permission_mode='view_and_take_action';f.c.oauth_scope=m.scopesForMode('view_and_take_action').join(' ');assert.equal((await f.svc.execute('user',args('prepare_design',design))).status,'prepared');assert.equal(f.calls.length,0);const proposal=await f.svc.execute('user',args('prepare_design',design),{runId:'run'});assert.equal(f.calls.length,0);const result=await f.svc.approve('user',proposal.step_id,'approve');assert.equal(result.result.verified,true);assert.equal(result.result.design_id,'D123');await f.svc.approve('user',proposal.step_id,'approve');assert.equal(f.calls.filter(c=>c.opts.method==='POST'&&c.url.endsWith('/designs')).length,1);});
test('reject, another user, reconnect and mode downgrade cannot execute an old approval',async()=>{const f=fixture();f.c.permission_mode='view_and_take_action';f.c.oauth_scope=m.scopesForMode('view_and_take_action').join(' ');const a=await f.svc.execute('user',args('prepare_design',design),{runId:'run'});assert.equal(await f.svc.approve('other',a.step_id,'approve'),null);f.c.permission_mode='view_only';assert.equal((await f.svc.approve('user',a.step_id,'approve')).ok,false);await f.svc.approve('user',a.step_id,'reject');assert.equal(f.calls.length,0);});
test('disconnect blocks reads and token refresh; reconnect issues a new PKCE state',async()=>{const f=fixture();await f.svc.disconnect('user');await assert.rejects(f.svc.execute('user',args('list_designs')),/Connect/);const start=await f.svc.start('user','https://marina.example','/');assert.ok(start.authorizeUrl);assert.equal((await f.svc.callback(f.states()[0].state,'code',null)).ok,true);assert.equal(f.c.status,'connected');});
test('missing callback scope is resolved by introspection, never assumed from request',async()=>{const f=fixture({omitScope:true});f.c.status='auth_required';await f.svc.start('user','https://marina.example','/');assert.equal((await f.svc.callback(f.states()[0].state,'code',null)).ok,true);assert.ok(f.calls.some(c=>c.url.endsWith('/oauth/introspect')));assert.equal(f.c.oauth_scope,m.scopesForMode('view_only').join(' '));});
test('temporary refresh failure preserves connection; confirmed invalid grant requires reconnect',async()=>{for(const status of [503,400]){const f=fixture({fetch:async(url)=>url.endsWith('/oauth/token')?{ok:false,status,json:async()=>({error:status===400?'invalid_grant':'server_error'})}:null});f.c.token_expires_at='2000-01-01';await assert.rejects(f.svc.token('user'),/refresh failed/);assert.equal(f.c.status,status===400?'auth_required':'connected');}});
test('uncertain create response cannot cause an automatic or repeated approval write',async()=>{const f=fixture({fetch:async(url,opts)=>{if(url.endsWith('/designs')&&opts.method==='POST')throw Error('timeout');}});f.c.permission_mode='view_and_take_action';f.c.oauth_scope=m.scopesForMode('view_and_take_action').join(' ');const a=await f.svc.execute('user',args('prepare_design',design),{runId:'run'});assert.equal((await f.svc.approve('user',a.step_id,'approve')).ok,false);await f.svc.approve('user',a.step_id,'approve');assert.equal(f.actions[0].status,'unknown');assert.equal(f.calls.filter(c=>c.opts.method==='POST'&&c.url.endsWith('/designs')).length,1);});
test('reauthorization invalidates previously prepared design approval',async()=>{const f=fixture();f.c.permission_mode='view_and_take_action';f.c.oauth_scope=m.scopesForMode('view_and_take_action').join(' ');const a=await f.svc.execute('user',args('prepare_design',design),{runId:'run'});f.c.oauth_connected_at='2026-09-23T00:00:00.000Z';assert.equal((await f.svc.approve('user',a.step_id,'approve')).ok,false);assert.equal(f.calls.length,0);});
