const {test}=require('node:test');const assert=require('node:assert/strict');const {merge}=require('../ecosystem-update');
test('brand update retains private notes and unrelated businesses',()=>{const old={brand_voice:'old',private_about:'private',ecosystem:{businesses:[{id:'one',name:'One',type:'affiliate',goal:'Keep goal'}],priorityId:'one'}};const next=merge(old,{brand_voice:'Direct',tone_traits:['Warm']});assert.equal(next.brand_voice,'Direct');assert.equal(next.private_about,'private');assert.deepEqual(next.ecosystem,old.ecosystem);assert.equal(old.brand_voice,'old');});
test('business upserts preserve existing goals and other businesses',()=>{const old={ecosystem:{businesses:[{id:'one',name:'One',type:'affiliate',goal:'Keep goal'},{id:'two',name:'Two',type:'other'}],priorityId:'one'}};const next=merge(old,{businesses:[{id:'one',offers:'New offer'},{id:'three',name:'Three',type:'network_marketing'}]});assert.equal(next.ecosystem.businesses.length,3);assert.equal(next.ecosystem.businesses[0].goal,'Keep goal');assert.equal(next.ecosystem.priorityId,'one');});
test('rejects private writes, invalid priorities and malformed patches',()=>{assert.throws(()=>merge({},{private_about:'overwrite'}));assert.throws(()=>merge({},{priorityId:'foreign'}));assert.throws(()=>merge({},{tone_traits:'wrong'}));assert.throws(()=>merge({},{businesses:[{id:'new',name:'Bad',type:'invalid'}]}));});
test('actual action handler writes form fields only to authenticated user and confirms database result',async()=>{
 const fs=require('node:fs'),vm=require('node:vm');const source=fs.readFileSync(require.resolve('../api.js'),'utf8');const start=source.indexOf('async function executeActionTool(');const end=source.indexOf('\nasync function ',start+1);let saved;
 const ctx={ECOSYSTEM_UPDATE:require('../ecosystem-update'),nextActionStepOrder:async()=>1,getMemory:async id=>{assert.equal(id,'owner');return {brand_brain:{private_about:'keep'}}},sbRest:async(path,opts)=>{saved=JSON.parse(opts.body)[0];assert.equal(saved.user_id,'owner');return [{brand_brain:saved.brand_brain}]}};
 vm.createContext(ctx);vm.runInContext(source.slice(start,end),ctx);
 const result=await ctx.executeActionTool({name:'update_my_ecosystem',args:{patch_json:JSON.stringify({brand_voice:'Warm and direct'})},userId:'owner',conversationId:'chat',runId:'run'});
 assert.equal(saved.brand_brain.brand_voice,'Warm and direct');assert.equal(saved.brand_brain.private_about,'keep');assert.equal(result.ok,true);
 ctx.sbRest=async()=>[];await assert.rejects(()=>ctx.executeActionTool({name:'update_my_ecosystem',args:{patch_json:'{}'},userId:'owner',runId:'run'}),/not confirmed/);
});
test('chat resource review preserves uploaded original and other references',()=>{const old={ecosystem:{priorityId:'one',businesses:[{id:'one',type:'affiliate',name:'One',resources:[{id:'plan',kind:'compensation',attachment:{storagePath:'owner/plan.pdf'},summary:'Old'},{id:'rules',kind:'policies',summary:'Keep'}]}]}};const next=merge(old,{businesses:[{id:'one',resources:[{id:'plan',kind:'compensation',summary:'Reviewed'}]}]});assert.equal(next.ecosystem.businesses[0].resources[0].attachment.storagePath,'owner/plan.pdf');assert.equal(next.ecosystem.businesses[0].resources[1].summary,'Keep');assert.throws(()=>merge(old,{businesses:[{id:'one',resources:[{id:'hack',kind:'policies',attachment:{storagePath:'other/file'}}]}]}));});
