const {test}=require('node:test');const assert=require('node:assert/strict');
const {createService}=require('../google/service');const m=require('../google/manifest');
function fixture(options={}){
 const key=options.key||'gmail';
 let c={integration_key:key,status:'connected',permission_mode:'view_only',oauth_scope:m.providers[key].scopes.join(' '),token_expires_at:new Date(Date.now()+3600000).toISOString(),oauth_connected_at:'2026-09-22T00:00:00.000Z'},access='old-access',refresh='old-refresh',lease=null,states=[],actions=[],steps=[],calls=[],saveFailures=options.saveFailures||0;
 const response=(data,status=200)=>({ok:status<300,status,json:async()=>data,text:async()=>JSON.stringify(data)});
 const sbRest=async(path,opts={})=>{const [table,query]=path.split('?'),q=new URLSearchParams(query),body=opts.body?JSON.parse(opts.body):null;
 if(table==='user_connections'){if(opts.method==='PATCH'){if(q.has('status')&&!q.get('status').slice(4,-1).split(',').includes(c.status))return [];Object.assign(c,body);return [];}return [{...c}];}
 if(table==='connection_oauth_states'){if(opts.method==='POST'){states.push(...body);return [];}const matches=states.filter(s=>q.get('state')==='eq.'+s.state);if(opts.method==='DELETE')states=states.filter(s=>!matches.includes(s));return matches;}
 if(table==='canva_design_actions'){if(opts.method==='POST'){actions.push(...body);return [];}const a=actions.find(a=>q.get('step_id')==='eq.'+a.step_id&&q.get('user_id')==='eq.'+a.user_id);if(!a||(q.get('status')&&q.get('status')!=='eq.'+a.status))return [];if(opts.method==='PATCH')Object.assign(a,body);return [{...a}];}
 if(table==='action_steps')return [];
 throw Error('Unexpected DB route '+table);};
 const sbRpc=async(name,p)=>{assert.equal(name,'google_token_transition');const a=p.p_action;if(a==='disconnect'){c.status='disabled';access=refresh=null;states=[];lease=null;return true;}if(['disabled','disconnected'].includes(c.status))return false;if(a==='claim'){if(lease)return false;lease=p.p_lease;return true;}if(lease!==p.p_lease)return false;if(a==='release'){lease=null;return true;}if(a==='revoke'){c.status='auth_required';return true;}if(a==='scopes'){c.oauth_scope=p.p_data.scope;return true;}if(a==='save'){if(saveFailures-->0)throw Error('temporary storage error');access=p.p_data.access_token;refresh=p.p_data.refresh_token;c.token_expires_at=new Date(Date.now()+3600000).toISOString();if('scope'in p.p_data)c.oauth_scope=p.p_data.scope;c.status='connected';return true;}throw Error('Unknown transition');};
 const fetchImpl=async(url,opts)=>{calls.push({url,opts});if(options.fetch){const custom=await options.fetch(url,opts);if(custom)return custom;}if(url==='https://oauth2.googleapis.com/token'){assert.equal(new URLSearchParams(opts.body).get('client_id'),'fixed-client');const form=new URLSearchParams(opts.body);if(form.get('grant_type')==='refresh_token')assert.equal(form.get('refresh_token'),refresh);return response({access_token:'new-access-'+calls.length,...(options.omitRefresh?{}:{refresh_token:'new-refresh-'+calls.length}),expires_in:3600,...(options.omitScope?{}:{scope:options.scope??c.oauth_scope})});}if(url.endsWith('/oauth/introspect'))return response({active:true,scope:m.providers[key].scopes.join(' ')});if(url.endsWith('/designs')&&opts.method==='POST')return response({design:{id:'D123'}});if(url.endsWith('/designs/D123'))return response({design:{id:'D123',urls:{edit_url:'https://www.canva.com/design/D123/edit'}}});return response({items:[]});};
 const svc=createService(key,{sbRest,sbRpc,getSecret:async()=>access,getRefreshSecret:async()=>refresh,fetchImpl,env:options.env??{GOOGLE_CLIENT_ID:'fixed-client',GOOGLE_CLIENT_SECRET:'test-secret'},insertActionStep:async step=>{const s={...step,id:'step-'+steps.length};steps.push(s);return s;},nextActionStepOrder:async()=>steps.length+1});
 return {svc,c,calls,steps,actions,response,access:()=>access,refresh:()=>refresh,states:()=>states};
}
const args=(operation,parameters={})=>({operation,parameters_json:JSON.stringify(parameters)});
const design={title:'Test design',width:1080,height:1080};

test('each provider requests only its read scopes, offline access and one-use PKCE callback',async()=>{for(const key of Object.keys(m.providers)){const f=fixture({key});f.c.status='auth_required';const start=await f.svc.start('user','https://marina.example','/');const u=new URL(start.authorizeUrl);assert.equal(u.origin,'https://accounts.google.com');assert.equal(u.searchParams.get('access_type'),'offline');assert.equal(u.searchParams.get('scope'),m.providers[key].scopes.join(' '));assert.equal(u.searchParams.get('redirect_uri'),'https://marina.example/api/connections/oauth/callback');assert.equal(u.searchParams.get('code_challenge_method'),'S256');assert.equal((await f.svc.callback(u.searchParams.get('state'),'code',null)).ok,true);assert.equal(await f.svc.callback(u.searchParams.get('state'),'code',null),null);}});
test('omitted refresh token and scope preserve stored authorization through refresh and reload',async()=>{const f=fixture({omitRefresh:true,omitScope:true});f.c.token_expires_at='2000-01-01';await f.svc.execute('user',args('list_messages'));assert.equal(f.refresh(),'old-refresh');assert.equal(f.c.oauth_scope,m.providers.gmail.scopes.join(' '));assert.equal((await f.svc.row('user')).status,'connected');await f.svc.execute('user',args('list_messages'));assert.equal(f.calls.filter(x=>x.url==='https://oauth2.googleapis.com/token').length,1);});
test('rotation replaces returned refresh token; concurrent expiry refreshes once',async()=>{const f=fixture();f.c.token_expires_at='2000-01-01';await Promise.all([f.svc.execute('user',args('list_messages')),f.svc.execute('user',args('list_messages'))]);assert.notEqual(f.refresh(),'old-refresh');assert.equal(f.calls.filter(x=>x.url==='https://oauth2.googleapis.com/token').length,1);});
test('all provider diagnostics read before and after refresh without writes',async()=>{for(const key of Object.keys(m.providers)){const f=fixture({key});const result=await f.svc.verify('user');assert.equal(result.refresh,'passed');assert.ok(result.checks.every(c=>c.status==='passed'));assert.equal(result.status,'connected');assert.ok(f.calls.filter(c=>c.url!=='https://oauth2.googleapis.com/token').every(c=>c.opts.method==='GET'));}});
test('missing scopes and cancelled upgrade keep connected; unsupported writes fail closed in both modes',async()=>{const f=fixture();f.c.oauth_scope='';assert.equal((await f.svc.execute('user',args('list_messages'))).error,'reauthorization_required');await f.svc.start('user','https://marina.example','/');assert.equal((await f.svc.callback(f.states()[0].state,'','access_denied')).ok,false);assert.equal(f.c.status,'connected');for(const mode of ['view_only','view_and_take_action']){f.c.permission_mode=mode;await assert.rejects(f.svc.execute('user',args('send_email')),/Unsupported/);}assert.equal(f.calls.length,0);});
test('cross-provider and arbitrary parameter calls are blocked',async()=>{const f=fixture();await assert.rejects(f.svc.execute('user',args('list_files')),/Unsupported/);await assert.rejects(f.svc.execute('user',args('list_messages',{url:'https://evil.example'})),/Unsupported/);assert.equal(f.calls.length,0);});
test('temporary errors retain connection; confirmed invalid_grant requires reauthorization',async()=>{for(const status of [500,400]){const f=fixture({fetch:async url=>url==='https://oauth2.googleapis.com/token'?{ok:false,status,json:async()=>({error:status===400?'invalid_grant':'server_error'})}:null});f.c.token_expires_at='2000-01-01';await assert.rejects(f.svc.token('user'));assert.equal(f.c.status,status===400?'auth_required':'connected');}});
test('disconnect clears local credentials and rejects old callbacks',async()=>{const f=fixture();f.c.oauth_scope='';await f.svc.start('user','https://marina.example','/');const state=f.states()[0].state;await f.svc.disconnect('user');assert.equal(f.access(),null);assert.equal(f.refresh(),null);assert.equal(await f.svc.callback(state,'code',null),null);await assert.rejects(f.svc.execute('user',args('list_messages')),/Connect/);});
