const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');const source=fs.readFileSync('api.js','utf8');
const lifecycle=source.slice(source.indexOf('async function bmodTransition('),source.indexOf('async function testBmodConnection('));
function context(extra={}){const calls=[];const ctx=vm.createContext({require,Date,URL,URLSearchParams,AbortSignal,console,process:{env:{HIGHLEVEL_CLIENT_ID:'client',HIGHLEVEL_CLIENT_SECRET:'secret'}},setTimeout,BMOD_MANIFEST:{VERSION:'test',parseScopes:s=>new Set(s.split(' '))},bmodGrantedTools:()=>[],BMOD_RECONNECT_ERROR:'reconnect',sbRest:async path=>{calls.push(['row',path]);return [{status:'connected',oauth_provider:'highlevel',token_expires_at:new Date(Date.now()+3600000).toISOString(),oauth_scope:'contacts.readonly'}]},sbRpc:async(name,args)=>{calls.push([name,args]);return true},getConnectionSecret:async(id,key)=>{calls.push(['secret',key]);return key+'-token'},...extra});vm.runInContext(lifecycle,ctx);return {ctx,calls};}
test('business and corporate tokens use independent rows and RPCs',async()=>{const {ctx,calls}=context();assert.equal(await ctx.getHighLevelAccessToken('owner'),'bmod_tools-token');assert.equal(await ctx.getHighLevelAccessToken('owner','bmod_membership'),'bmod_membership-token');await ctx.bmodTransition('owner','claim','lease',{},'bmod_membership');await ctx.bmodTransition('owner','disconnect');assert.match(calls[0][1],/integration_key=eq.bmod_tools/);assert.match(calls[2][1],/integration_key=eq.bmod_membership/);assert.equal(calls[4][0],'membership_token_transition');assert.equal(calls[5][0],'bmod_token_transition');});
test('corporate token refresh keeps every read and write in corporate storage',async()=>{const seen=[];const {ctx,calls}=context({sbRest:async path=>{seen.push(path);return [{status:'connected',oauth_provider:'highlevel',token_expires_at:'2000-01-01',oauth_scope:'contacts.readonly'}]},getConnectionRefreshSecret:async(id,key)=>{seen.push(key);return 'refresh'},fetchJsonMaybe:async()=>({response:{ok:true},data:{access_token:'new',refresh_token:'new-refresh',expires_in:3600}})});assert.equal(await ctx.getHighLevelAccessToken('owner','bmod_membership'),'new');assert.ok(seen.every(x=>x.includes('bmod_membership')));assert.ok(calls.filter(x=>x[0].includes('transition')).every(x=>x[0]==='membership_token_transition'));});
const helpers=source.slice(source.indexOf('async function membershipConfig('),source.indexOf('async function completeBmodOAuth('));
test('wrong corporate location is rejected without saving tokens',async()=>{let saved=0;const ctx=vm.createContext({require,Date,sbRest:async()=>[{value:{connection_user_id:'owner',location_id:'corporate'}}],bmodTransition:async()=>true,exchangeOAuthCode:async()=>({locationId:'personal',scope:'contacts.readonly'}),saveBmodTokens:async()=>saved++});vm.runInContext(helpers,ctx);await assert.rejects(ctx.completeMembershipOAuth({user_id:'owner',expires_at:new Date(Date.now()+100000).toISOString()},'code'),/corporate BMOD/);assert.equal(saved,0);});
test('corporate OAuth saves only to separate storage and rejects expired states',async()=>{let key;const ctx=vm.createContext({require,Date,sbRest:async()=>[{value:{connection_user_id:'owner',location_id:'corporate'}}],bmodTransition:async()=>true,exchangeOAuthCode:async()=>({locationId:'corporate',scope:'contacts.readonly'}),saveBmodTokens:async(id,lease,data,k)=>{key=k}});vm.runInContext(helpers,ctx);await ctx.completeMembershipOAuth({user_id:'owner',expires_at:new Date(Date.now()+100000).toISOString()},'code');assert.equal(key,'bmod_membership');await assert.rejects(ctx.completeMembershipOAuth({user_id:'owner',expires_at:'invalid'},'code'),/expired/);});
test('corporate connection is excluded from customer and model connection lists',async()=>{const ctx=vm.createContext({sbRest:async()=>[{integration_key:'bmod_membership'}]});vm.runInContext(source.slice(source.indexOf('async function getConnectionsForUser('),source.indexOf('async function getConnectionSecret(')),ctx);assert.equal((await ctx.getConnectionsForUser('owner')).length,0);});
test('corporate setup supplies required connection and OAuth state fields',async()=>{const writes=[];const ctx=vm.createContext({Date,URL,randomUrlSafe:n=>'x'.repeat(n),process:{env:{HIGHLEVEL_CLIENT_ID:'client',HIGHLEVEL_CLIENT_SECRET:'secret'}},sbRest:async(path,options)=>{if(!options)return [{value:{connection_user_id:'owner',location_id:'corporate'}}];writes.push({path,row:JSON.parse(options.body)[0]});return []}});vm.runInContext(helpers,ctx);const result=await ctx.startMembershipOAuth('owner','https://mod.example.com');assert.equal(writes[0].row.server_url,'https://services.leadconnectorhq.com');assert.equal(writes[1].row.code_verifier.length,48);assert.equal(writes[1].row.integration_key,'bmod_membership');assert.equal(new URL(result.authorizeUrl).searchParams.get('scope'),'contacts.readonly');});
