const {test}=require('node:test');const assert=require('node:assert/strict');const {accessFromTags,createMembershipService}=require('../access/membership');
const fs=require('node:fs');const vm=require('node:vm');const source=fs.readFileSync(require('node:path').join(__dirname,'../api.js'),'utf8');
test('active corporate BMOD and MOD tags independently grant access',()=>{for(const tags of [['BMOD Client'],['MOD Sale'],[' bmod client ','MOD SALE']])assert.equal(accessFromTags(tags).active,true);});
test('inactive tag overrides active tag for its product, other active product still grants access',()=>{assert.equal(accessFromTags(['bmod client','bmod terminated']).active,false);assert.equal(accessFromTags(['mod sale','mod inactive']).active,false);assert.equal(accessFromTags(['bmod client','bmod terminated','mod sale']).active,true);assert.equal(accessFromTags(['bmod client','mod sale','mod inactive']).active,true);assert.equal(accessFromTags(['bmod client','bmod terminated','mod sale','mod inactive']).active,false);});
test('missing or unrelated tags deny access',()=>{for(const tags of [null,[],['bmod coach'],['mod inactive']])assert.equal(accessFromTags(tags).active,false);});
function fixture(contacts){const calls=[];let linked={provider_account_id:'corporate'};const service=createMembershipService({sbRest:async()=>[{value:{connection_user_id:'owner',location_id:'corporate'}}],connection:async()=>linked,call:async(...args)=>{calls.push(args);return {contacts};}});return {service,calls,disconnect:()=>linked=null};}
test('only exact email in the configured corporate account supplies the grant',async()=>{const f=fixture([{email:'somebody@example.com',tags:['mod sale']},{email:'Member@Example.com',locationId:'corporate',tags:['bmod client']}]);assert.equal((await f.service.check(' member@example.com ')).active,true);assert.equal(f.calls[0][0],'owner');assert.equal(f.calls[0][2].body.locationId,'corporate');assert.equal(f.calls[0][2].body.query,'member@example.com');assert.deepEqual(f.calls[0][2].requiredScopes,['contacts.readonly']);});
test('missing member denies, duplicate matches and wrong location fail closed',async()=>{assert.equal((await fixture([]).service.check('x@example.com')).active,false);for(const contacts of [[{email:'x@example.com'},{email:'x@example.com'}],[{email:'x@example.com',locationId:'other',tags:['mod sale']}]])await assert.rejects(fixture(contacts).service.check('x@example.com'),/UNAVAILABLE/);});
test('disconnected corporate account prevents checking instead of trusting a stale grant',async()=>{const f=fixture([]);f.disconnect();await assert.rejects(f.service.check('x@example.com'),/UNAVAILABLE/);assert.equal(f.calls.length,0);});
test('each request rechecks tags so cancellation takes effect without signing out',async()=>{const contacts=[{email:'member@example.com',tags:['mod sale']}];const f=fixture(contacts);assert.equal((await f.service.check('member@example.com')).active,true);contacts[0].tags.push('mod inactive');assert.equal((await f.service.check('member@example.com')).active,false);assert.equal(f.calls.length,2);});
test('prototype bypass is ignored; owner management access is separate',async()=>{const ctx=vm.createContext({process:{env:{PROTOTYPE_ALLOW_ALL_AUTHENTICATED:'true'}},isControlRoomAdmin:e=>e==='owner',MEMBERSHIP:{check:async()=>({active:false})}});vm.runInContext(source.slice(source.indexOf('async function hasAccess('),source.indexOf('\nasync function createConversation(')),ctx);assert.equal(await ctx.hasAccess('id','member'),false);assert.equal(await ctx.hasAccess('id','owner'),true);});
test('all authenticated app routes have a subscription gate before connections, images and chat',()=>{const gate=source.indexOf('code:"ACCESS_INACTIVE"');assert.ok(gate>source.indexOf('await verifyUser(req)'));for(const route of ['const googleRoute=','path === "/api/images/status"','path === "/api/chat"'])assert.ok(gate<source.indexOf(route));const verify=source.slice(source.indexOf('async function verifyUser('),source.indexOf('\nasync function sbRest('));assert.doesNotMatch(verify,/ALLOWED_TEST_EMAILS|NOT_ALLOWED/);});
