const {test}=require('node:test');const assert=require('node:assert/strict');const vm=require('node:vm');const fs=require('node:fs');
const html=fs.readFileSync(require('node:path').join(__dirname,'../index.html'),'utf8');
function fixture(){
 const input={value:'Existing draft',focus(){}},button={setAttribute(){}},note={},timers=[],calls=[];let stopped=0,recorder;
 class Recorder{static isTypeSupported(t){return t==='audio/mp4';}constructor(stream,opts){recorder=this;this.mimeType=opts.mimeType;this.state='inactive';}start(){this.state='recording';}stop(){this.state='inactive';this.ondataavailable({data:new Blob(['speech'],{type:this.mimeType})});this.done=this.onstop();}}
 const ctx=vm.createContext({voiceCapture:{generation:0},state:{page:'chat',conversationId:'chat',session:{user:{id:'alice'}}},qs:s=>s==='#input'?input:s==='#dictateBtn'?button:note,document:{querySelectorAll:()=>[]},navigator:{mediaDevices:{getUserMedia:async()=>({getTracks:()=>[{stop:()=>stopped++}]})}},window:{MediaRecorder:Recorder},MediaRecorder:Recorder,Blob,setInterval:fn=>0,clearInterval(){},setTimeout:fn=>{timers.push(fn);return 1;},clearTimeout(){},api:async(...args)=>{calls.push(args);return {text:'My voice prompt'};}});
 vm.runInContext(html.slice(html.indexOf('function stopModVoice('),html.indexOf('function voiceControls(')),ctx);
 return {ctx,input,button,note,timers,calls,recorder:()=>recorder,stopped:()=>stopped};
}
test('dictation stops at two minutes and appends editable text without sending',async()=>{const f=fixture();await f.ctx.toggleDictation();assert.equal(f.recorder().mimeType,'audio/mp4');f.timers[0]();await f.recorder().done;assert.equal(f.input.value,'Existing draft My voice prompt');assert.equal(f.calls[0][0],'/api/voice/transcribe');assert.equal(f.calls.length,1);assert.match(f.note.textContent,/Review your words/);assert.ok(f.stopped()>0);assert.equal(f.ctx.voiceCapture.busy,false);});
test('navigating away cancels dictation and releases microphone without transcription',async()=>{const f=fixture();await f.ctx.toggleDictation();f.ctx.stopModVoice(true);await f.recorder().done;assert.equal(f.calls.length,0);assert.equal(f.input.value,'Existing draft');assert.ok(f.stopped()>0);});
test('microphone permission denial preserves draft and restores button',async()=>{const f=fixture();f.ctx.navigator.mediaDevices.getUserMedia=async()=>{const e=Error();e.name='NotAllowedError';throw e;};await f.ctx.toggleDictation();assert.match(f.note.textContent,/denied/);assert.equal(f.button.disabled,false);assert.equal(f.input.value,'Existing draft');});
