const {test}=require('node:test');const assert=require('node:assert/strict');const {Readable}=require('node:stream');const {createVoiceService,readRecording,spokenText,MAX_RECORDING_BYTES}=require('../voice/service');
function fixture(){
 const usage=[],calls=[];let duration=10,failSpeech=false;const messages=[{id:'reply',user_id:'alice',role:'assistant',content:'**Hello**, Queen.'}];
 const service=createVoiceService({storageHeaders:()=>({}),sbRest:async(path,opts={})=>{
  const [table,query]=path.split('?'),q=new URLSearchParams(query),rows=table==='messages'?messages:usage;const match=r=>[...q].every(([k,v])=>!v.startsWith('eq.')||String(r[k])===v.slice(3));
  if(opts.method==='POST'){const data=JSON.parse(opts.body);const inserted=[];for(const row of data){if(row.cache_key&&usage.some(x=>x.cache_key===row.cache_key))continue;usage.push(row);inserted.push(row);}return inserted;}
  if(opts.method==='PATCH'){rows.filter(match).forEach(r=>Object.assign(r,JSON.parse(opts.body)));return [];}
  return rows.filter(match).map(x=>({...x}));
 },fetcher:async(url,opts)=>{calls.push({url,opts});if(url.includes('/sign/'))return {ok:true,json:async()=>({signedURL:'/object/sign/mod-voice/alice/cached.mp3?token=private'})};if(url.includes('/storage/'))return {ok:true};if(url.includes('transcriptions'))return {ok:true,json:async()=>({text:'My spoken prompt',duration})};return {ok:!failSpeech,arrayBuffer:async()=>Buffer.from('mp3 audio')};}});
 return {service,usage,calls,messages,setDuration:v=>duration=v,fail:()=>failSpeech=true};
}
test('dictation returns reviewable text, records duration separately, and stores no recording',async()=>{const f=fixture();const r=await f.service.transcribe('alice',{bytes:Buffer.from('audio'),mime:'audio/webm'});assert.equal(r.text,'My spoken prompt');assert.equal(f.usage[0].kind,'dictation');assert.equal(f.usage[0].duration_seconds,10);assert.equal(f.usage[0].status,'completed');assert.equal(f.calls.filter(x=>x.url.includes('/storage/')).length,0);});
test('playback is owner-scoped, cached privately, and replay avoids another paid call',async()=>{const f=fixture();await assert.rejects(f.service.playback('bob','reply'),/not found/);assert.equal(f.calls.length,0);const first=await f.service.playback('alice','reply');assert.equal(first.cached,false);const replay=await f.service.playback('alice','reply');assert.equal(replay.cached,true);assert.equal(f.calls.filter(x=>x.url.includes('/audio/speech')).length,1);assert.equal(f.usage[0].kind,'playback');assert.match(f.usage[0].storage_path,/^alice\//);});
test('concurrent playback requests reserve only one generation',async()=>{const f=fixture();const results=await Promise.all([f.service.playback('alice','reply'),f.service.playback('alice','reply')]);assert.ok(results.some(x=>x.pending));assert.equal(f.calls.filter(x=>x.url.includes('/audio/speech')).length,1);});
test('failed generation is recorded and never automatically regenerated',async()=>{const f=fixture();f.fail();await assert.rejects(f.service.playback('alice','reply'));await assert.rejects(f.service.playback('alice','reply'));assert.equal(f.usage[0].status,'failed');assert.equal(f.calls.filter(x=>x.url.includes('/audio/speech')).length,1);});
test('raw recording rejects oversized or unsupported uploads before transcription',async()=>{for(const [mime,bytes] of [['text/html',Buffer.from('x')],['audio/webm',Buffer.alloc(MAX_RECORDING_BYTES+1)]]){const req=Readable.from([bytes]);req.headers={'content-type':mime};await assert.rejects(readRecording(req));}const req=Readable.from([Buffer.from('sample')]);req.headers={'content-type':'audio/webm;codecs=opus'};assert.equal((await readRecording(req)).mime,'audio/webm');});
test('long recording and overlong playback fail with useful limits',async()=>{const f=fixture();f.setDuration(125);await assert.rejects(f.service.transcribe('alice',{bytes:Buffer.from('audio'),mime:'audio/mp4'}),/two minutes/);f.messages[0].content='a'.repeat(4001);await assert.rejects(f.service.playback('alice','reply'),/shorter spoken summary/);});
test('speech removes markup, URLs and fenced code without changing ordinary words',()=>{assert.equal(spokenText('## Hello **Queen** [read more](https://example.com)'),'Hello Queen read more');assert.match(spokenText('Before\n```js\nsecret()\n```\nAfter'),/Before[\s\S]*Code example omitted[\s\S]*After/);});
